version: "3.9"

services:
  master:
    image: locustio/locust
    ports:
      - "8099:8089"
    volumes:
      - ./dj_millionaires_service/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --master -H http://master:8089

  worker:
    image: locustio/locust
    volumes:
      - ./dj_millionaires_service/:/mnt/locust
    command: -f /mnt/locust/locustfile.py --worker --master-host master

  db:
    image: postgres
    restart: always
    volumes:
      - ./dj_millionaires_service/data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  dj_millionaires_service:
    build:
      context: ./dj_millionaires_service
      dockerfile: dj_millionaires_service.dockerfile
    command: ./prestart.sh
    volumes:
      - ./dj_millionaires_service/:/code
      - ./dj_millionaires_service/static:/code/static
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_NAME=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - DJANGO_SUPERUSER_PASSWORD=admin
    depends_on:
      - db
    restart: always

  fastapi_todo_backend:
    build:
      context: ./fastapi_todo_backend
      dockerfile: fastapi_todo_backend.dockerfile
    volumes:
      - ./fastapi_todo_backend/:/code
    ports:
      - "8002:80"
    restart: always

