# Generated by Django 4.0.3 on 2022-03-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_millionaire_company_alter_millionaire_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='name',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
