# Generated by Django 4.0.3 on 2022-04-25 23:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_millionaire_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='VoteMillionaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('millionaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='core.millionaire')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
