# Generated by Django 4.0.3 on 2022-04-26 23:39

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_millionaire_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='millionaire',
            name='vector_column',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='millionaire',
            index=django.contrib.postgres.indexes.GinIndex(fields=['vector_column'], name='core_millio_vector__32459a_gin'),
        ),
    ]
