# Generated by Django 4.0.3 on 2022-03-24 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_country_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millionaire',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='millionaires', to='core.company'),
        ),
        migrations.AlterField(
            model_name='millionaire',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='millionaires', to='core.country'),
        ),
    ]
