# Generated by Django 4.0.3 on 2022-04-26 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_votemillionaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millionaire',
            name='image',
            field=models.ImageField(default='profile_pics/system_default.jpg', upload_to='profile_pics/'),
        ),
    ]
