# Generated by Django 4.0.3 on 2022-04-26 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_millionaire_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='millionaire',
            name='image',
            field=models.ImageField(default='profile_pics/system_default.png', upload_to='profile_pics/'),
        ),
    ]
