# Generated by Django 4.0.3 on 2023-09-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_userprofile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Millionaire'), (1, 'Business'), (3, 'Admin'), (2, 'User')], default=2),
        ),
    ]
